# Generated by Django 5.2.17 on 2026-09-01 02:42

import core.phone
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('phone_number', models.CharField(help_text='Stored in E.164 format, e.g. +9779800000000.', max_length=20, unique=True, validators=[core.phone.validate_phone_number])),
                ('country_code', models.CharField(blank=True, help_text='Dialling code derived from the phone number, e.g. 977.', max_length=5)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('invalid', 'Invalid number'), ('blocked', 'Blocked')], db_index=True, default='active', max_length=16)),
                ('opted_in', models.BooleanField(db_index=True, default=False, help_text='Only opted-in contacts can be included in a campaign.')),
                ('opt_in_source', models.CharField(blank=True, choices=[('manual', 'Entered manually by an operator'), ('csv_import', 'CSV import with explicit consent column'), ('web_form', 'Sign-up form'), ('inbound_message', 'Recipient messaged us first'), ('unknown', 'Not recorded')], max_length=32)),
                ('opt_in_at', models.DateTimeField(blank=True, null=True)),
                ('opt_out_source', models.CharField(blank=True, choices=[('manual', 'Removed by an operator'), ('inbound_stop', 'Recipient replied STOP'), ('csv_import', 'CSV import without consent'), ('provider', 'Reported by the messaging provider')], max_length=32)),
                ('opt_out_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_error_code', models.CharField(blank=True, max_length=32)),
                ('last_error_message', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ['name', 'phone_number'],
            },
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contact group',
                'verbose_name_plural': 'contact groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('not_opted_in_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='contacts.contactgroup')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contact import',
                'verbose_name_plural': 'contact imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(help_text='1-based, excluding the header row.')),
                ('outcome', models.CharField(choices=[('imported', 'Imported'), ('updated', 'Updated existing contact'), ('duplicate', 'Duplicate phone number'), ('invalid', 'Invalid data')], db_index=True, max_length=16)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='contacts.contact')),
                ('contact_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='contacts.contactimport')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_additions', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='contacts.contact')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='contacts.contactgroup')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='groups', through='contacts.GroupMembership', to='contacts.contact'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['opted_in', 'status'], name='contact_eligibility_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['-created_at'], name='contact_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(('phone_number__startswith', '+')), name='contact_phone_is_e164'),
        ),
        migrations.AddIndex(
            model_name='contactimportrow',
            index=models.Index(fields=['contact_import', 'outcome'], name='import_row_outcome_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'contact'], name='membership_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('contact', 'group'), name='unique_contact_per_group'),
        ),
    ]
