# Generated by Django 5.2.17 on 2026-09-04 03:42

import core.phone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_require_organization'),
        ('organizations', '0002_backfill_default_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(db_index=True, help_text='Stored in E.164 format, e.g. +9779800000000.', max_length=20, validators=[core.phone.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('organization', 'phone_number'), name='unique_contact_phone_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='contactgroup',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_group_name_per_organization'),
        ),
    ]
