# Generated by Django 5.2.17 on 2026-09-04 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_phone_number_alter_contactgroup_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactChannelConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], db_index=True, max_length=16)),
                ('opted_in', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('opted_in_at', models.DateTimeField(blank=True, null=True)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_consents', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'channel consent',
                'verbose_name_plural': 'channel consents',
                'indexes': [models.Index(fields=['channel', 'opted_in'], name='consent_channel_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('contact', 'channel'), name='unique_consent_per_contact_channel')],
            },
        ),
    ]
