# Generated by Django 5.2.17 on 2026-09-03 19:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_backfill_default_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='summary')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Leave empty for 'pricing on request'. Do not invent a placeholder.", max_digits=10, null=True, verbose_name='price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=16, verbose_name='interval')),
                ('max_contacts', models.PositiveIntegerField(blank=True, help_text='Empty means unlimited.', null=True, verbose_name='contact limit')),
                ('max_messages_per_month', models.PositiveIntegerField(blank=True, help_text='Empty means unlimited.', null=True, verbose_name='messages per month')),
                ('max_team_members', models.PositiveIntegerField(blank=True, help_text='Empty means unlimited.', null=True, verbose_name='team members')),
                ('trial_days', models.PositiveSmallIntegerField(default=0, verbose_name='trial days')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_public', models.BooleanField(default=True, help_text='Show this plan on the pricing page.', verbose_name='public')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='features')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='trialing', max_length=16)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField()),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Cancels when the paid period runs out rather than immediately.')),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
                ('plan', models.ForeignKey(help_text='PROTECT: deleting a plan customers are on would erase what they bought.', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'indexes': [models.Index(fields=['status', 'current_period_end'], name='subscription_renewal_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('current_period_end__gt', models.F('current_period_start'))), name='subscription_period_is_forward')],
            },
        ),
        migrations.CreateModel(
            name='UsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('contacts_at_close', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_snapshots', to='billing.plan')),
            ],
            options={
                'verbose_name': 'usage snapshot',
                'verbose_name_plural': 'usage snapshots',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'period_start'), name='unique_usage_period')],
            },
        ),
    ]
