# Generated by Django 5.2.17 on 2026-08-31 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'User logged in'), ('login_failed', 'Login attempt failed'), ('logout', 'User logged out'), ('contact_created', 'Contact created'), ('contact_updated', 'Contact updated'), ('contact_deleted', 'Contact deleted'), ('contact_opted_in', 'Contact opted in'), ('contact_opted_out', 'Contact opted out'), ('contacts_imported', 'Contacts imported from CSV'), ('campaign_created', 'Campaign created'), ('campaign_launched', 'Campaign launched'), ('campaign_paused', 'Campaign paused'), ('campaign_resumed', 'Campaign resumed'), ('campaign_cancelled', 'Campaign cancelled'), ('templates_synced', 'Templates synced from provider')], db_index=True, max_length=64)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='core_auditl_object__42e4a9_idx'), models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx')],
            },
        ),
    ]
