# Generated by Django 5.2.17 on 2026-09-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User logged in'), ('login_failed', 'Login attempt failed'), ('logout', 'User logged out'), ('contact_created', 'Contact created'), ('contact_updated', 'Contact updated'), ('contact_deleted', 'Contact deleted'), ('contact_opted_in', 'Contact opted in'), ('contact_opted_out', 'Contact opted out'), ('contacts_imported', 'Contacts imported from CSV'), ('campaign_created', 'Campaign created'), ('campaign_launched', 'Campaign launched'), ('campaign_paused', 'Campaign paused'), ('campaign_resumed', 'Campaign resumed'), ('campaign_cancelled', 'Campaign cancelled'), ('templates_synced', 'Templates synced from provider'), ('report_exported', 'Report exported')], db_index=True, max_length=64),
        ),
    ]
