# Generated by Django 5.2.17 on 2026-09-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_registered', 'Account registered'), ('email_verified', 'Email address verified'), ('login', 'User logged in'), ('login_failed', 'Login attempt failed'), ('logout', 'User logged out'), ('contact_created', 'Contact created'), ('contact_updated', 'Contact updated'), ('contact_deleted', 'Contact deleted'), ('contact_opted_in', 'Contact opted in'), ('contact_opted_out', 'Contact opted out'), ('contacts_imported', 'Contacts imported from CSV'), ('campaign_created', 'Campaign created'), ('campaign_launched', 'Campaign launched'), ('campaign_paused', 'Campaign paused'), ('campaign_resumed', 'Campaign resumed'), ('campaign_cancelled', 'Campaign cancelled'), ('templates_synced', 'Templates synced from provider'), ('report_exported', 'Report exported'), ('subscription_started', 'Subscription started'), ('subscription_changed', 'Subscription plan changed'), ('subscription_cancelled', 'Subscription cancelled'), ('invoice_issued', 'Invoice issued'), ('invoice_paid', 'Invoice paid'), ('invoice_voided', 'Invoice voided')], db_index=True, max_length=64),
        ),
    ]
