# Generated by Django 5.2.17 on 2026-09-04 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_auditlog_action'),
        ('organizations', '0002_backfill_default_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('campaign_finished', 'A campaign finished sending'), ('campaign_failed', 'A campaign finished with heavy failures'), ('quota_warning', 'A plan limit is nearly spent'), ('quota_reached', 'A plan limit has been reached'), ('payment_failed', 'A payment did not go through'), ('invoice_issued', 'An invoice was issued'), ('sender_problem', 'A WhatsApp sender stopped working')], db_index=True, max_length=32)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notification_user_recent_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('campaign_finished', 'A campaign finished sending'), ('campaign_failed', 'A campaign finished with heavy failures'), ('quota_warning', 'A plan limit is nearly spent'), ('quota_reached', 'A plan limit has been reached'), ('payment_failed', 'A payment did not go through'), ('invoice_issued', 'An invoice was issued'), ('sender_problem', 'A WhatsApp sender stopped working')], max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
                'constraints': [models.UniqueConstraint(fields=('user', 'kind'), name='unique_notification_preference')],
            },
        ),
    ]
