# Generated by Django 5.2.17 on 2026-09-03 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('timezone', models.CharField(default='UTC', help_text='Used when presenting dates and grouping reports.', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='active', max_length=16)),
                ('owner', models.ForeignKey(help_text='The account ultimately responsible for this organization.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('member', 'Member')], default='member', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization member',
                'verbose_name_plural': 'organization members',
                'ordering': ['organization__name', 'user__email'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status', 'name'], name='org_status_name_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['user', 'organization'], name='member_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_member_per_organization'),
        ),
    ]
