# Generated by Django 5.2.17 on 2026-09-01 03:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('contacts', '0001_initial'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_phone_number', models.CharField(max_length=20)),
                ('message_type', models.CharField(choices=[('template', 'Approved template'), ('text', 'Free-form text (service window only)')], default='template', max_length=16)),
                ('template_name', models.CharField(blank=True, max_length=512)),
                ('template_language', models.CharField(blank=True, max_length=16)),
                ('rendered_payload', models.JSONField(blank=True, default=dict)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', help_text="The provider's message id (Meta calls this a wamid).", max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contacts.contact')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp.messagetemplate')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['contact__name'],
            },
        ),
        migrations.CreateModel(
            name='MessageStatusEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], max_length=16)),
                ('source', models.CharField(choices=[('webhook', 'Provider webhook'), ('send_response', 'Provider send response'), ('system', 'System')], default='webhook', max_length=16)),
                ('provider_timestamp', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='messaging.message')),
            ],
            options={
                'verbose_name': 'message status event',
                'verbose_name_plural': 'message status events',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['campaign', 'status'], name='message_campaign_status_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status', 'next_retry_at'], name='message_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['contact', '-created_at'], name='message_contact_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('campaign', 'contact'), name='unique_message_per_campaign_contact'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_message_id', ''), _negated=True), fields=('provider_message_id',), name='unique_provider_message_id'),
        ),
        migrations.AddIndex(
            model_name='messagestatusevent',
            index=models.Index(fields=['message', 'created_at'], name='status_event_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagestatusevent',
            constraint=models.UniqueConstraint(fields=('message', 'status', 'provider_timestamp'), name='unique_status_event_per_message'),
        ),
    ]
