# Generated by Django 5.2.17 on 2026-09-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestatusevent',
            name='source',
            field=models.CharField(choices=[('webhook', 'Provider webhook'), ('send_response', 'Provider send response'), ('system', 'System'), ('simulated', 'Simulated (mock provider)')], default='webhook', max_length=16),
        ),
    ]
