# Generated by Django 5.2.17 on 2026-09-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_require_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], db_index=True, default='whatsapp', max_length=16),
        ),
    ]
