# Generated by Django 5.2.17 on 2026-09-01 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('template', 'Approved template'), ('text', 'Free-form text (service window only)')], default='template', max_length=16)),
                ('body_text', models.TextField(blank=True)),
                ('variable_mapping', models.JSONField(blank=True, default=dict)),
                ('target_all_eligible', models.BooleanField(default=False, help_text='Target every opted-in, active contact instead of specific groups.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='whatsapp.messagetemplate')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_entries', to='campaigns.campaign')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_entries', to='contacts.contactgroup')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='audience_groups',
            field=models.ManyToManyField(blank=True, related_name='campaigns', through='campaigns.CampaignAudience', to='contacts.contactgroup'),
        ),
        migrations.AddConstraint(
            model_name='campaignaudience',
            constraint=models.UniqueConstraint(fields=('campaign', 'group'), name='unique_group_per_campaign'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', '-created_at'], name='campaign_status_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['scheduled_at'], name='campaign_scheduled_idx'),
        ),
    ]
