# Generated by Django 5.2.17 on 2026-09-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_require_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], db_index=True, default='whatsapp', max_length=16, verbose_name='channel'),
        ),
    ]
