# Generated by Django 5.2.17 on 2026-09-01 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The template name as registered with Meta, e.g. order_ready.', max_length=512)),
                ('language', models.CharField(default='en_US', help_text='Language and locale code, e.g. en_US.', max_length=16)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utility'), ('authentication', 'Authentication')], default='utility', max_length=32)),
                ('source', models.CharField(choices=[('synced', 'Synced from Meta'), ('local', 'Local (development only)')], default='local', max_length=16)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending review'), ('rejected', 'Rejected'), ('paused', 'Paused'), ('disabled', 'Disabled'), ('not_submitted', 'Not submitted to Meta')], db_index=True, default='not_submitted', max_length=16)),
                ('header_text', models.CharField(blank=True, max_length=60)),
                ('body_text', models.TextField(help_text='Use {{1}} or {{name}} for variables.')),
                ('footer_text', models.CharField(blank=True, max_length=60)),
                ('variables', models.JSONField(blank=True, default=list, help_text='Ordered placeholder tokens found in the header and body.')),
                ('example_values', models.JSONField(blank=True, default=dict)),
                ('provider_template_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message template',
                'verbose_name_plural': 'message templates',
                'ordering': ['name', 'language'],
                'indexes': [models.Index(fields=['source', 'status'], name='template_usability_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'language'), name='unique_template_name_language')],
            },
        ),
    ]
