# Generated by Django 5.2.17 on 2026-09-02 05:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('rejected', 'Rejected (bad signature)')], db_index=True, default='received', max_length=16)),
                ('status_count', models.PositiveIntegerField(default=0, help_text='Delivery statuses found in this payload.')),
                ('message_count', models.PositiveIntegerField(default=0, help_text='Inbound messages found in this payload.')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'webhook event',
                'verbose_name_plural': 'webhook events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='webhook_status_recent_idx')],
            },
        ),
    ]
