# Generated by Django 5.2.17 on 2026-09-04 03:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_backfill_default_organization'),
        ('whatsapp', '0004_require_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='meta', help_text='Matches a key in whatsapp.services.factory.PROVIDERS.', max_length=32, verbose_name='provider')),
                ('label', models.CharField(blank=True, help_text='What this number is for.', max_length=100, verbose_name='label')),
                ('phone_number_id', models.CharField(max_length=64, unique=True, verbose_name='phone number id')),
                ('waba_id', models.CharField(blank=True, max_length=64, verbose_name='WABA id')),
                ('display_phone_number', models.CharField(blank=True, max_length=32)),
                ('verified_name', models.CharField(blank=True, max_length=128)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('unverified', 'Not verified yet'), ('active', 'Active'), ('disabled', 'Disabled')], db_index=True, default='unverified', max_length=16)),
                ('is_default', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'messaging account',
                'verbose_name_plural': 'messaging accounts',
                'ordering': ['-is_default', 'created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='msgacct_org_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization',), name='one_default_messaging_account_per_organization')],
            },
        ),
    ]
