# Generated by Django 5.2.17 on 2026-09-04 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_backfill_default_organization'),
        ('whatsapp', '0006_backfill_messaging_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='messagetemplate',
            name='unique_template_name_language',
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'language'), name='unique_template_name_language'),
        ),
    ]
